import json
Q=[
("s1",1,"In battery language, what does a C-rate of 2C on a 100 Ah cell describe?",
 ["A current of 200 A, twice the cell's capacity in amperes","A cell voltage of 2 V above nominal","A charge that takes two hours to complete","A capacity that has faded to twice its internal resistance"],0,
 "C-rate expresses current relative to capacity, so 2C on a 100 Ah cell is 200 A (1.2).","C-rate definition"),
("s1",2,"A carmaker moves a platform from 400 V to 800 V while delivering the same power. What happens in the cabling?",
 ["Current halves and resistive heat loss falls to a quarter","Current halves and heat loss halves with it","Current doubles but the thicker cable absorbs the heat","Current is unchanged; only charging speed improves"],0,
 "Heat loss scales with current squared, so halving current cuts loss to one quarter (1.1).","Voltage and I squared R"),
("s1",3,"A two-wheeler team is told to cut energy use in city riding. Which lever does the source point to first?",
 ["Mass, because it dominates stop-start city driving","Drag coefficient, because drag power rises with speed cubed","Frontal area, because it sets aerodynamic loss at all speeds","Gear ratio, because it fixes rolling resistance"],0,
 "Mass hurts far more in stop-start city driving than on the highway, and aerodynamics matters less at low 2W speeds (1.4).","Road load priorities"),
("s2",1,"Which architecture has a battery, no engine, and is recharged by plugging in?",
 ["BEV, battery electric vehicle","HEV, hybrid electric vehicle","MHEV, mild hybrid electric vehicle","FCEV, fuel cell electric vehicle"],0,
 "A BEV draws energy from the battery only and plugs in to recharge; HEVs and MHEVs do not plug in (2).","Architecture families"),
("s2",2,"What separates a series hybrid from a parallel hybrid?",
 ["In a series hybrid the wheels are always driven by the motor; the engine only charges","In a series hybrid the engine always drives the wheels directly","A parallel hybrid cannot recharge its battery from braking","A parallel hybrid uses a planetary gear set by definition"],0,
 "A series hybrid's engine only charges the battery while the motor always drives the wheels (2.1).","Hybrid sub-types"),
("s3",1,"What is the SEI in a lithium-ion cell?",
 ["A film that forms on the anode, protecting it but thickening over life and consuming lithium","A separator coating that blocks thermal runaway above 130 degrees Celsius","The busbar interface between two series cell groups","A sensor layer the BMS uses to read cell temperature"],0,
 "The solid electrolyte interphase protects the anode but thickens over life, consuming lithium and causing capacity fade (3.1).","SEI and capacity fade"),
("s3",2,"An Indian e-3W fleet operator runs high daily kilometres in hot conditions. Which chemistry does the source favour, and why?",
 ["LFP, for safety, cost and cycle life","NCA, for the highest energy per kilogram","LTO, because cost is not a constraint in fleets","Lead-acid, because it tolerates heat best"],0,
 "For India's heat, low-cost segments and high daily usage, LFP usually wins on safety, cost and life (3.2).","Chemistry trade-off"),
("s3",3,"A pack is specified as 16S with LFP cells. What nominal pack voltage should you expect?",
 ["About 51 V","About 58 V","About 64 V","About 350 V"],0,
 "LFP is about 3.2 V nominal, so 16 series groups give roughly 51 V, a common 2W and 3W pack (3.5).","Series configuration"),
("s3",4,"A cell in test reaches about 130 degrees Celsius. What is the next event in the thermal runaway sequence?",
 ["The separator melts, creating an internal short circuit","The SEI layer begins to break down and release heat","The cathode breaks down and releases oxygen","Flammable gas vents and the cell catches fire"],0,
 "SEI breakdown comes first at 80 to 120 C; separator melt and internal short follow at about 130 C, before cathode breakdown at 150 to 250 C (3.7).","Runaway sequence"),
("s3",3,"Why does a pack need a pre-charge circuit before the main contactor closes?",
 ["The inverter's large capacitors would otherwise draw an inrush current that welds the contactors","The BMS needs time to read every cell voltage before current flows","The cells must be balanced before any load is applied","The insulation monitor cannot run once the contactor is closed"],0,
 "A resistor path charges the inverter capacitors slowly so inrush current does not weld the contactors (3.5).","Pre-charge circuit"),
("s4",1,"What does the inverter do in a BEV powertrain?",
 ["Converts battery DC into three-phase AC of the frequency and amplitude the motor needs","Converts grid AC into DC for the battery","Steps the high-voltage pack down to 12 V for lights and ECUs","Balances cell voltages across the series groups"],0,
 "The inverter converts battery DC into variable three-phase AC for the traction motor; the OBC and DC-DC do the other jobs (4.5).","Inverter function"),
("s4",2,"Why are SiC MOSFETs described as essential for most 800 V systems?",
 ["They offer lower losses and higher temperature capability than IGBTs","They are cheaper than IGBTs at every voltage","They remove the need for a DC link capacitor","They allow the motor to run without a position sensor"],0,
 "Silicon carbide MOSFETs have lower losses and higher temperature capability, which is what 800 V systems need (4.5).","Wide-bandgap switches"),
("s4",3,"A supplier quotes a motor at 60 kW. What should you ask before accepting the number?",
 ["Whether that is peak or continuous, and for how long at what temperature","Whether it was measured with a resolver or Hall sensors","Whether the rotor uses hairpin or round wire windings","Whether the figure includes the gearbox reduction ratio"],0,
 "Peak power is allowed for seconds while continuous is what the motor can hold without overheating; marketing sheets often quote peak only (4.3).","Peak versus continuous"),
("s5",2,"Why is DC fast charging normally quoted as a 10 to 80 percent time?",
 ["Above roughly 80 percent SOC the BMS cuts current sharply to protect the cells","The charger cannot hold a constant voltage above 80 percent","Most connectors overheat beyond 80 percent state of charge","Billing meters stop recording above 80 percent"],0,
 "DC charging is fast to roughly 80 percent SOC, after which the BMS cuts current sharply (5.1).","The charging curve"),
("s5",1,"What does OCPP govern?",
 ["How chargers talk to a back-end server for billing, monitoring and remote control","How the vehicle and charger negotiate current over the control pilot","How a pack is tested for thermal propagation","How AC is converted to DC inside the onboard charger"],0,
 "Open Charge Point Protocol is the charger-to-back-end protocol; ISO 15118 covers car-to-charger communication (5.4).","Charging protocols"),
("s5",3,"A customer installs a 22 kW wallbox but their car charges at only 7.2 kW. What is the most likely cause?",
 ["The vehicle's onboard charger is rated 7.2 kW, and it limits AC charging speed","The wallbox is wired for DC fast charging, not AC","The battery is above 80 percent state of charge","The Type 2 connector cannot carry more than 7.2 kW"],0,
 "The onboard charger's rating limits AC charging speed no matter how large the wall charger is (4.7).","Onboard charger limit"),
("s6",3,"A pack runs 6 degrees Celsius hotter at its centre than at its edges. Why does the source treat that as a problem?",
 ["Cells age at different rates and the pack is limited by its worst cell; target a spread under about 5 C","Uneven temperature trips the HVIL and shuts down high voltage","A spread above 5 C invalidates the IP67 rating","The BMS cannot run coulomb counting with unequal temperatures"],0,
 "Uneven temperature makes cells age at different rates, and the pack is limited by its worst cell; the target spread is under about 5 C (6.1).","Thermal uniformity"),
("s6",2,"Which cooling method does the source associate with most cars, buses and premium two-wheelers?",
 ["Indirect liquid cooling with water-glycol through cold plates","Forced air pushed through the pack by fans","Phase change material absorbing heat as it melts","Immersion in a dielectric fluid"],0,
 "Indirect liquid cooling gives even temperatures and supports fast charging, at the cost of weight and leak risk (6.2).","Cooling methods"),
("s7",1,"When the driver presses the accelerator, what does the VCU do with the request?",
 ["Picks the lowest of driver request, battery power limit, motor thermal limit and traction limit","Passes it straight to the inverter as a current command","Sends it to the BMS, which decides the final torque","Splits it evenly between regen and friction braking"],0,
 "The VCU always picks the lowest of those four limits before issuing a torque command (7.2).","Torque request flow"),
("s7",2,"You are debugging a CAN bus and need to know what a message's bytes mean. Which artefact do you open?",
 ["The DBC file, which defines each CAN message and signal","The DVP&R, which lists the validation tests","The DFMEA, which scores failure modes","The PPAP file from the supplier"],0,
 "The DBC file is the dictionary defining what each CAN message and signal means (7.3).","CAN tooling"),
("s8",2,"What does a skateboard platform give a vehicle programme?",
 ["A flat floor battery between the axles, a low centre of gravity and flexible body options","A two-speed gearbox that improves both launch and top speed","A lighter vehicle than an equivalent petrol car","Freedom from crash protection requirements under the floor"],0,
 "The skateboard puts a flat battery in the floor between the axles, giving a low centre of gravity and flexible top-hat bodies (8.2).","Platform architecture"),
("s9",2,"What does PPAP confirm before production starts?",
 ["That a supplier can make parts consistently","That the vehicle has passed type approval","That every requirement traces to a test","That the pack meets its IP67 rating"],0,
 "The production part approval process confirms a supplier can make parts consistently before production starts (9.2).","Production readiness"),
("s9",3,"An end-of-line pack test finds a failure that the source names as a top cause of field problems. Which is it?",
 ["Weld quality at the cell interconnects","Incorrect cell chemistry in the bill of materials","Software flashed to the wrong ECU","An oversized DC link capacitor"],0,
 "Weld quality at cell joining is called out as a top cause of field failures (9.4).","Pack manufacturing risk"),
("s10",2,"Why are many Indian two-wheeler packs designed to sit just under 60 V?",
 ["Above 60 V DC counts as high voltage and triggers extra protection rules","Below 60 V the BMS is not required at all","Charging connectors above 60 V are not sold in India","AIS-156 does not apply to packs above 60 V"],0,
 "Up to 60 V DC counts as low voltage in most EV standards; above it, high-voltage protection rules apply (10.1).","Voltage classes"),
("s10",2,"Which requirement belongs to Phase 2 of India's 2022 battery safety amendments rather than Phase 1?",
 ["At least four temperature sensors in the BMS","Pack traceability","An additional safety fuse","Cell-to-cell spacing"],0,
 "Traceability, an extra fuse and cell spacing are Phase 1; four temperature sensors, EMC testing and thermal propagation testing are Phase 2 (10.3).","AIS-156 phases"),
("s10",3,"A technician is about to work on a high-voltage pack. What does the source require after removing the service disconnect?",
 ["Verify zero voltage with a rated meter that has itself been tested first","Close the contactors to discharge the DC link","Remove insulated gloves so torque can be felt on the busbar bolts","Start work immediately, since the MSD has split the pack voltage"],0,
 "The five steps are switch off, remove and secure the disconnect, verify zero voltage with a rated meter that is tested first, wait for capacitor discharge, then cover live parts (10.5).","HV work procedure"),
("s11",3,"A supplier claims 90 km of real-world range for an e-scooter with a 2 kWh pack. Does the claim survive a sanity check?",
 ["No — at 25 to 40 Wh/km, 2 kWh supports roughly 50 to 80 km","Yes — e-2W consumption is about 15 Wh/km","Yes — real-world range usually exceeds the certified figure","No — e-2W consumption is about 60 to 100 Wh/km, so the claim is far too high"],0,
 "At the rule of thumb of 25 to 40 Wh/km for an e-2W, 2 kWh gives roughly 50 to 80 km, so 90 km does not hold (11.1).","Consumption rules of thumb"),
("s11",4,"Field data shows early range loss and cell imbalance across a fleet. Which combination does the source point to?",
 ["Poorly matched cells, weak balancing and heat gradients — fix with grading, better balancing and even cooling","Loose busbars from wrong bolt torque — fix with torque-controlled tools","Water ingress through a failed seal — fix with leak testing at end of line","Gate driver design faults in the inverter — fix with snubbers and derating"],0,
 "Cell imbalance and early range loss trace to poorly matched cells, weak balancing and heat gradients (11.2).","Failure mode diagnosis"),
("s12",4,"A 30 kWh usable pack charges from 20 to 100 percent on a 7.2 kW onboard charger at 90 percent efficiency. Roughly how long?",
 ["About 3.7 hours, so plan around 4 hours with the slower top-up","About 3.3 hours, since efficiency applies only to DC charging","About 4.6 hours, because only 5.2 kW reaches the battery","About 2.7 hours, because 7.2 kW reaches the battery directly"],0,
 "24 kWh is needed and 6.5 kW reaches the battery, giving about 3.7 hours before the slower top-up phase (12.6).","AC charging time"),
("s12",4,"A motor delivers 200 Nm at 6,000 rpm. What is the shaft power?",
 ["About 126 kW","About 94 kW","About 152 kW","About 1,200 kW"],0,
 "Power in kW equals torque times rpm divided by 9,549, so 200 x 6,000 / 9,549 is about 126 kW (12.4).","Torque, speed and power"),
("s12",3,"For the worked highway case at 90 km/h, how does drag compare with rolling resistance?",
 ["Drag is already about twice rolling resistance","The two are roughly equal at that speed","Rolling resistance is about twice drag","Drag is negligible until about 120 km/h"],0,
 "Rolling force is 147 N against a drag force of 285 N, so drag is already about twice rolling resistance at 90 km/h (12.2).","Road load balance"),
]
out=[{"topic":t,"level":l,"stem":s,"options":o,"answer":a,"why":w,"concept":c} for (t,l,s,o,a,w,c) in Q]
json.dump(out, open("seed.json","w"), ensure_ascii=False)
print(len(out), "seed questions")
